#!/bin/bash
# Connects to the printer and prints the files

IP=10.42.0.1
PRINTER="HP-LaserJet-P2015-Series"
USER="guest"
TEMP_DESTINATION="~/Documents/printout"

source "printerParameters.sh"
FILE=""
# Parse commandline arguments
while [[ $# -gt 1 ]]
do
  key="$1"
  case $key in
    -file)
    FILE="$2"
    shift
    ;;
    *)
    echo "Unknown option!"
    ;;
  esac
  shift
done

echo "${TEMP_DESTINATION}"
if [ "$FILE" != "" ]
then
  # Create destination folder if it does not exist
  ssh ${USER}@${IP} "mkdir -p ""${TEMP_DESTINATION}"" "

  # Copy the files to the server
  scp ${FILE} ${USER}@${IP}:${TEMP_DESTINATION}

  # Print the file
  ssh ${USER}@${IP} "lp -d ""${PRINTER}"" ""${TEMP_DESTINATION}/${FILE}"" "
fi
